version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: kagemann-creatives-wp
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: kagemann_creatives
      WORDPRESS_DEBUG: 1
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads:/var/www/html/wp-content/uploads
    depends_on:
      - db
    networks:
      - kagemann-network

  db:
    image: mysql:8.0
    container_name: kagemann-creatives-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kagemann_creatives
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - kagemann-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kagemann-creatives-pma
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    depends_on:
      - db
    networks:
      - kagemann-network

volumes:
  db_data:

networks:
  kagemann-network:
    driver: bridge
